# Generated by Django 6.0 on 2026-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_article_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
