# Generated by Django 6.0 on 2025-12-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_category",
                    models.CharField(
                        max_length=150, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "description_category",
                    models.TextField(verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name_category"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(
                        max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "description_product",
                    models.TextField(verbose_name="Описание продукта"),
                ),
                (
                    "image_product",
                    models.ImageField(upload_to="images/", verbose_name="Изображения"),
                ),
                (
                    "category_product",
                    models.CharField(max_length=150, verbose_name="Категория продукта"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name_product"],
            },
        ),
    ]
