# Generated by Django 6.0 on 2025-12-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name_product", "category_product"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price_product",
            field=models.FloatField(default=0.0, verbose_name="Цена продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Products",
                to="catalog.category",
                verbose_name="Категория продукта",
            ),
        ),
    ]
