# Generated by Django 6.0 on 2026-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_price_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_product",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Изображения"
            ),
        ),
    ]
